export const themes = {
  listoka: {
    background: 'bg-darkest-gray',
    lightBackground: 'bg-light-gray',
    cardBackground: 'bg-darkest-gray',
    darkestBackground: 'bg-body-background',
    specialBackground: 'bg-brand-green',
    shadowEffect: 'shadowEffect', 
    standardBorder: 'border-medium-gray',
    specialBorder: 'border-brand-green',
    darkBorder: 'border-darkest-gray',
    darkestBorder: 'border-black',
    standardText: 'text-light-gray',
    specialText: 'text-brand-green',
    alternativeText: 'text-yahtzee-red',
    darkText: 'text-darkest-gray',
  },
  matador: {
    background: 'bg-darkest-gray',
    lightBackground: 'bg-light-gray',
    cardBackground: 'bg-darkest-gray',
    darkestBackground: 'bg-body-background',
    specialBackground: 'bg-gold',
    shadowEffect: 'shadowEffect', 
    standardBorder: 'border-medium-gray',
    specialBorder: 'border-yahtzee-red',
    darkBorder: 'border-darkest-gray',
    darkestBorder: 'border-black',
    standardText: 'text-light-gray',
    specialText: 'text-gold',
    alternativeText: 'text-yahtzee-red',
    darkText: 'text-darkest-gray',
  },
  light: {
    background: 'bg-white-gray',
    lightBackground: 'bg-body-background',
    cardBackground: 'bg-light-gray',
    darkestBackground: 'bg-white-gray',
    specialBackground: 'bg-dark-blue',
    shadowEffect: 'shadowEffect', 
    standardBorder: 'border-white',
    specialBorder: 'border-white',
    darkBorder: 'border-white',
    darkestBorder: 'border-white',
    standardText: 'text-darkest-gray',
    specialText: 'text-dark-blue',
    alternativeText: 'text-red-dark',
    darkText: 'text-light-gray',
  },
}

// No longer using Context
// export const ThemeContext = React.createContext(themes.listoka);